M48
; DRILL file KiCad 10.99.0-3671-gbe90a7e200 date 2026-09-10T00:13:49
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-10T00:13:49+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.99.0-3671-gbe90a7e200
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.016
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C2.500
%
G90
G05
T1
X1.524Y8.89
X8.382Y8.89
T2
X2.286Y2.54
X4.826Y2.54
X7.366Y2.54
T3
X5.08Y15.875
M30
