M48
; DRILL file KiCad 10.99.0-3758-g2f18d95be7 date 2026-09-12T18:32:53
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-12T18:32:53+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.99.0-3758-g2f18d95be7
; #@! TF.FileFunction,NonPlated,1,16,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X-1.95Y17.653
X1.95Y17.653
T2
X-11.811Y1.5
X-11.811Y-1.5
M30
