M48
; DRILL file KiCad 10.99.0-3671-gbe90a7e200 date 2026-09-09T22:56:29
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-09T22:56:29+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.99.0-3671-gbe90a7e200
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.540
%
G90
G05
T1
X6.533Y12.827
X13.983Y12.827
T2
X48.26Y20.32
X48.26Y2.54
M30
