M48
; DRILL file KiCad 10.99.0-3758-g2f18d95be7 date 2026-09-21T16:48:03
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-21T16:48:03+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.99.0-3758-g2f18d95be7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.286
%
G90
G05
T1
X15.367Y10.39
X15.367Y7.39
T2
X46.46Y12.64
X46.46Y5.14
T3
X3.175Y13.335
X3.175Y4.445
M30
