M48
; DRILL file KiCad 10.99.0-3758-g2f18d95be7 date 2026-09-22T01:02:21
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-22T01:02:21+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.99.0-3758-g2f18d95be7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.800
%
G90
G05
T1
X9.906Y33.274
T2
X14.406Y33.274
T3
X3.5Y52.5
X3.5Y3.5
X61.5Y52.5
X61.5Y3.5
M30
