M48
; DRILL file KiCad 10.99.0-3758-g2f18d95be7 date 2026-09-21T15:21:46
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-21T15:21:46+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.99.0-3758-g2f18d95be7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X8.75Y12.7
X16.2Y12.7
T2
X12.7Y12.962
M30
