M48
; DRILL file KiCad 10.99.0-3671-gbe90a7e200 date 2026-09-10T00:14:46
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-10T00:14:46+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.99.0-3671-gbe90a7e200
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X6.0Y22.549
X11.78Y22.549
T2
X15.875Y12.93
X15.875Y9.93
M30
