M48
; DRILL file KiCad 10.99.0-3758-g2f18d95be7 date 2026-09-25T21:15:48
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-25T21:15:48+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.99.0-3758-g2f18d95be7
; #@! TF.FileFunction,NonPlated,1,16,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X-1.95Y8.382
X1.95Y8.382
T2
X-6.096Y6.223
X6.096Y6.223
M30
