def main(**kwargs):
    options = kwargs.get("options", [])

    # Keep transistor definitions in a plain array. Adding another generic or
    # exact device should only require copying and editing one dictionary.
    transistors = [
        {
            "taxonomy": ["transistor", "sot_363_6", "mosfet", "n_channel", "dual"],
            "manufacturer": "",
            "part_number": "",
            "name_short": "Dual N-channel MOSFET SOT-363 (generic)",
        },
        {
            "taxonomy": ["transistor", "sot_23", "bipolar", "npn"],
            "manufacturer": "",
            "part_number": "",
            "name_short": "NPN Transistor SOT-23 (generic)",
        },
        {
            # Soldered boards draw bare "PNP" symbols on SOT-23-3 footprints
            # (PIR movement sensor Q2); mirror the generic NPN entry.
            "taxonomy": ["transistor", "sot_23", "bipolar", "pnp"],
            "manufacturer": "",
            "part_number": "",
            "name_short": "PNP Transistor SOT-23 (generic)",
        },
        {
            # Soldered boards draw bare "NMOS" symbols on SOT-23-3 footprints
            # (PIR movement sensor Q1); a value-less generic keeps them matchable
            # until a fitted BOM names the exact part.
            "taxonomy": ["transistor", "sot_23", "mosfet", "n_channel", "enhancement_mode"],
            "manufacturer": "",
            "part_number": "",
            "name_short": "N-channel MOSFET SOT-23 (generic)",
        },
        {
            "taxonomy": ["transistor", "sot_23", "bipolar", "pnp", "40_volt", "600_milliamp"],
            "manufacturer": "onsemi",
            "part_number": "mmbt4403",
            "name_short": "PNP Transistor MMBT4403",
        },
        {"taxonomy": ["transistor", "sot_23", "bipolar", "npn", "25_volt", "1_5_amp"],
         "manufacturer": "jsmsemi", "part_number": "ss8050", "name_short": "NPN Transistor SS8050"},
        {
            "taxonomy": [
                "transistor",
                "sot_23",
                "mosfet",
                "n_channel",
                "enhancement_mode",
                "60_volt",
            ],
            "manufacturer": "",
            "part_number": "2n7002",
            "name_short": "N-channel MOSFET 2N7002",
            "name_readable_override": "N-channel MOSFET 2N7002 SOT-23 (generic)",
        },
        {
            "taxonomy": [
                "transistor", "sot_23", "mosfet", "n_channel",
                "enhancement_mode", "60_volt", "300_milliamp",
            ],
            "manufacturer": "nexperia",
            "part_number": "2n7002_215",
            "name_short": "N-channel MOSFET 2N7002,215",
            "name_readable_override": "N-channel MOSFET 2N7002,215 SOT-23",
        },
        {
            "taxonomy": [
                "transistor", "sot_23", "mosfet", "n_channel",
                "enhancement_mode", "50_volt",
            ],
            "manufacturer": "",
            "part_number": "bss138",
            "name_short": "N-channel MOSFET BSS138",
            "name_readable_override": "N-channel MOSFET BSS138 SOT-23 (generic)",
        },
        {
            "taxonomy": [
                "transistor", "sot_23", "mosfet", "n_channel",
                "enhancement_mode", "50_volt", "220_milliamp",
            ],
            "manufacturer": "onsemi",
            "part_number": "bss138",
            "name_short": "N-channel MOSFET BSS138",
            "name_readable_override": "N-channel MOSFET BSS138 SOT-23",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_23",
                "mosfet",
                "n_channel",
                "enhancement_mode",
                "60_volt",
                "300_milliamp",
            ],
            "manufacturer": "cbi",
            "part_number": "mmbt7002k",
            "name_short": "N-channel MOSFET MMBT7002K",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_23",
                "bipolar",
                "npn",
                "160_volt",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "mmbt5551_range_200_300",
            "name_short": "NPN Transistor MMBT5551 (200-300)",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_23",
                "bipolar",
                "npn",
                "25_volt",
                "500_milliamp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "s8050_j3y_range_200_350",
            "name_short": "NPN Transistor S8050 J3Y (200-350)",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_23",
                "bipolar",
                "npn",
                "25_volt",
                "1_5_amp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "ss8050_range_200_350",
            "name_short": "NPN Transistor SS8050 (200-350)",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_23",
                "bipolar",
                "npn",
                "25_volt",
                "500_milliamp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "s9013_j3_range_200_350",
            "name_short": "NPN Transistor S9013 J3 (200-350)",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_23",
                "bipolar",
                "pnp",
                "150_volt",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "mmbt5401_range_200_300",
            "name_short": "PNP Transistor MMBT5401 (200-300)",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_23",
                "bipolar",
                "npn",
                "40_volt",
                "600_milliamp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "mmbt2222a_1p",
            "name_short": "NPN Transistor MMBT2222A 1P",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_23",
                "bipolar",
                "pnp",
                "25_volt",
                "1_5_amp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "ss8550_y2_range_200_350",
            "name_short": "PNP Transistor SS8550 Y2 (200-350)",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_23",
                "bipolar",
                "pnp",
                "25_volt",
                "500_milliamp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "s9012_2t1_range_200_350",
            "name_short": "PNP Transistor S9012 2T1 (200-350)",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_89_3",
                "bipolar",
                "npn",
                "30_volt",
                "3_amp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "d882_range_160_320",
            "name_short": "NPN Transistor D882 (160-320)",
        },
        {
            "taxonomy": [
                "transistor",
                "to_126",
                "bipolar",
                "npn",
                "30_volt",
                "3_amp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "d882_range_160_320",
            "name_short": "NPN Transistor D882 (160-320, TO-126)",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_23",
                "bipolar",
                "npn",
                "40_volt",
                "200_milliamp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "mmbt3904_range_100_300",
            "name_short": "NPN Transistor MMBT3904 (100-300)",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_23",
                "bipolar",
                "pnp",
                "25_volt",
                "500_milliamp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "s8550_range_120_200",
            "name_short": "PNP Transistor S8550 (120-200)",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_23",
                "mosfet",
                "n_channel",
                "enhancement_mode",
                "60_volt",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "2n7002",
            "name_short": "N-channel MOSFET 2N7002",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_23",
                "mosfet",
                "p_channel",
                "enhancement_mode",
                "20_volt",
            ],
            "manufacturer": "vishay",
            "part_number": "si2301cds_t1_ge3",
            "name_short": "P-channel MOSFET SI2301CDS-T1-GE3",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_23",
                "mosfet",
                "p_channel",
                "enhancement_mode",
                "30_volt",
            ],
            "manufacturer": "alpha_omega_semicon",
            "part_number": "ao3401a",
            "name_short": "P-channel MOSFET AO3401A",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_23",
                "mosfet",
                "n_channel",
                "enhancement_mode",
                "30_volt",
            ],
            "manufacturer": "alpha_omega_semicon",
            "part_number": "ao3400a",
            "name_short": "N-channel MOSFET AO3400A",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_523",
                "mosfet",
                "p_channel",
                "enhancement_mode",
                "20_volt",
                "2_8_amp",
            ],
            "manufacturer": "cbi",
            "part_number": "bc2301t_2_8a",
            "name_short": "P-channel MOSFET BC2301T-2.8A",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_363_6",
                "bipolar",
                "pnp",
                "dual_matched_pair",
                "45_volt",
                "100_milliamp",
            ],
            "manufacturer": "diodes_incorporated",
            "part_number": "bcm857bs_7_f",
            "name_short": "Dual matched PNP BCM857BS-7-F",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_363_6",
                "bipolar",
                "pnp",
                "dual_general_purpose",
                "40_volt",
                "200_milliamp",
            ],
            "manufacturer": "cbi",
            "part_number": "mmdt3906dw",
            "name_short": "Dual PNP MMDT3906DW",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_89_3",
                "bipolar",
                "pnp",
                "50_volt",
                "2_amp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "2sa1213_range_120_240",
            "name_short": "PNP Transistor 2SA1213 (120-240)",
        },
        {
            "taxonomy": [
                "transistor",
                "to_92",
                "bipolar",
                "npn",
                "40_volt",
                "200_milliamp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "2n3904_ta_range_200_300",
            "name_short": "NPN Transistor 2N3904-TA (200-300)",
        },
        {
            "taxonomy": [
                "transistor",
                "to_92",
                "bipolar",
                "pnp",
                "150_volt",
                "600_milliamp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "2n5401_ta_range_150_200",
            "name_short": "PNP Transistor 2N5401-TA (150-200)",
        },
        {
            "taxonomy": [
                "transistor",
                "to_92",
                "bipolar",
                "npn",
                "160_volt",
                "600_milliamp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "2n5551_ta_range_200_300",
            "name_short": "NPN Transistor 2N5551-TA (200-300)",
        },
        {
            "taxonomy": [
                "transistor",
                "to_92",
                "bipolar",
                "pnp",
                "25_volt",
                "1_5_amp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "8550ss_ta_range_160_300",
            "name_short": "PNP Transistor 8550SS-TA (160-300)",
        },
        {
            "taxonomy": [
                "transistor",
                "to_92",
                "bipolar",
                "pnp",
                "50_volt",
                "100_milliamp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "a733_ta_range_200_400",
            "name_short": "PNP Transistor A733-TA (200-400)",
        },
        {
            "taxonomy": [
                "transistor",
                "to_92",
                "bipolar",
                "pnp",
                "400_volt",
                "200_milliamp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "a94_ta",
            "name_short": "PNP Transistor A94-TA",
        },
        {
            "taxonomy": [
                "transistor",
                "to_92",
                "bipolar",
                "npn",
                "45_volt",
                "100_milliamp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "bc547_ta_range_200_450",
            "name_short": "NPN Transistor BC547-TA (200-450)",
        },
        {
            "taxonomy": [
                "transistor",
                "to_92",
                "bipolar",
                "npn",
                "50_volt",
                "150_milliamp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "c945_ta_range_200_400",
            "name_short": "NPN Transistor C945-TA (200-400)",
        },
        {
            "taxonomy": [
                "transistor",
                "to_92",
                "bipolar",
                "npn",
                "45_volt",
                "100_milliamp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "s9014_ta_range_200_600",
            "name_short": "NPN Transistor S9014-TA (200-600)",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_23",
                "bipolar",
                "pnp",
                "50_volt",
                "100_milliamp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "2sa812_range_300_400",
            "name_short": "PNP Transistor 2SA812 (300-400)",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_23",
                "bipolar",
                "npn",
                "50_volt",
                "100_milliamp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "2sc1623_range_300_400",
            "name_short": "NPN Transistor 2SC1623 (300-400)",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_23",
                "bipolar",
                "pnp",
                "50_volt",
                "150_milliamp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "a1015_range_120_240",
            "name_short": "PNP Transistor A1015 (120-240)",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_23",
                "bipolar",
                "npn",
                "45_volt",
                "500_milliamp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "bc817_range_100_250",
            "name_short": "NPN Transistor BC817 (100-250)",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_23",
                "bipolar",
                "npn",
                "45_volt",
                "100_milliamp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "bc847_1g_range_420_800",
            "name_short": "NPN Transistor BC847 1G (420-800)",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_23",
                "bipolar",
                "pnp",
                "45_volt",
                "100_milliamp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "bc857_range_420_800",
            "name_short": "PNP Transistor BC857 (420-800)",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_23",
                "bipolar",
                "pnp",
                "40_volt",
                "200_milliamp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "mmbt3906_2a_range_100_300",
            "name_short": "PNP Transistor MMBT3906 2A (100-300)",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_23",
                "bipolar",
                "npn",
                "40_volt",
                "600_milliamp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "mmbt4401_range_100_300",
            "name_short": "NPN Transistor MMBT4401 (100-300)",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_23",
                "bipolar",
                "pnp",
                "25_volt",
                "500_milliamp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "s8550_2ty_range_200_350",
            "name_short": "PNP Transistor S8550 2TY (200-350)",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_23",
                "bipolar",
                "npn",
                "45_volt",
                "100_milliamp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "s9014",
            "name_short": "NPN Transistor S9014",
        },
        {
            "taxonomy": [
                "transistor",
                "sot_23",
                "bipolar",
                "pnp",
                "45_volt",
                "100_milliamp",
            ],
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "s9015_range_300_400",
            "name_short": "PNP Transistor S9015 (300-400)",
        },
        # First TO-220AB power MOSFET in the family: Infineon IRF1010EPBF
        # (60 V, 83 A, 12 mOhm @ 10 V, 170 W).
        {
            "taxonomy": [
                "transistor",
                "to_220ab",
                "mosfet",
                "n_channel",
                "enhancement_mode",
                "60_volt",
                "83_amp",
            ],
            "manufacturer": "infineon_technologies",
            "part_number": "irf1010epbf",
            "name_short": "N-channel MOSFET IRF1010EPBF (TO-220AB)",
        },
        # IRF-series TO-220AB power MOSFETs from the JLC house-parts queue.
        # Ratings below are as printed on each staged JLC page.
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "55_volt", "169_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irf1405pbf",
            "name_short": "N-channel MOSFET IRF1405PBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "75_volt", "75_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irf2807pbf",
            "name_short": "N-channel MOSFET IRF2807PBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "55_volt", "110_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irf3205pbf",
            "name_short": "N-channel MOSFET IRF3205PBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "100_volt", "57_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irf3710pbf",
            "name_short": "N-channel MOSFET IRF3710PBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "p_channel",
                         "enhancement_mode", "55_volt", "74_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irf4905pbf",
            "name_short": "P-channel MOSFET IRF4905PBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "100_volt", "17_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irf530npbf",
            "name_short": "N-channel MOSFET IRF530NPBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "100_volt", "33_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irf540npbf",
            "name_short": "N-channel MOSFET IRF540NPBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "200_volt", "9_3_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irf630npbf",
            "name_short": "N-channel MOSFET IRF630NPBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "200_volt", "18_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irf640npbf",
            "name_short": "N-channel MOSFET IRF640NPBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "400_volt", "10_amp"],
            "manufacturer": "vishay_intertech",
            "part_number": "irf740pbf",
            "name_short": "N-channel MOSFET IRF740PBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "500_volt", "4_5_amp"],
            "manufacturer": "vishay_intertech",
            "part_number": "irf830pbf",
            "name_short": "N-channel MOSFET IRF830PbF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "p_channel",
                         "enhancement_mode", "100_volt", "14_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irf9530npbf",
            "name_short": "P-channel MOSFET IRF9530NPBF (TO-220AB)",
        },
        # IRF9540N carries the plain TO-220 label on its JLC page (the same
        # JEDEC body as TO-220AB); the label is kept as printed.
        {
            "taxonomy": ["transistor", "to_220", "mosfet", "p_channel",
                         "enhancement_mode", "100_volt", "23_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irf9540npbf",
            "name_short": "P-channel MOSFET IRF9540NPBF (TO-220)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "p_channel",
                         "enhancement_mode", "55_volt", "12_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irf9z24npbf",
            "name_short": "P-channel MOSFET IRF9Z24NPBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "75_volt", "180_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfb3207pbf",
            "name_short": "N-channel MOSFET IRFB3207PBF (TO-220AB)",
        },
        # TO-247AC power bodies (the -3 suffix on the Vishay page is the same
        # 3-lead outline; one token covers both page labels).
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "n_channel",
                         "enhancement_mode", "200_volt", "30_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfp250npbf",
            "name_short": "N-channel MOSFET IRFP250NPBF (TO-247AC)",
        },
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "n_channel",
                         "enhancement_mode", "500_volt", "20_amp"],
            "manufacturer": "vishay_intertech",
            "part_number": "irfp460apbf",
            "name_short": "N-channel MOSFET IRFP460APBF (TO-247AC-3)",
        },
        # DPAK (TO-252) power bodies: the page labels DPAK(TO-252AA) and
        # TO-252 are the same outline, so one token covers them.
        {
            "taxonomy": ["transistor", "to_252", "mosfet", "n_channel",
                         "enhancement_mode", "55_volt", "17_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfr024ntrpbf",
            "name_short": "N-channel MOSFET IRFR024NTRPBF (DPAK)",
        },
        {
            "taxonomy": ["transistor", "to_252", "mosfet", "n_channel",
                         "enhancement_mode", "200_volt", "5_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfr220ntrpbf",
            "name_short": "N-channel MOSFET IRFR220NTRPBF (DPAK)",
        },
        {
            "taxonomy": ["transistor", "to_252", "mosfet", "p_channel",
                         "enhancement_mode", "55_volt", "11_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfr9024ntrpbf",
            "name_short": "P-channel MOSFET IRFR9024NTRPBF (DPAK)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "55_volt", "49_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfz44npbf",
            "name_short": "N-channel MOSFET IRFZ44NPBF (TO-220AB)",
        },
        # Logic-level SOT-23 MOSFETs.
        {
            "taxonomy": ["transistor", "sot_23", "mosfet", "n_channel",
                         "enhancement_mode", "20_volt", "1_2_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irlml2402trpbf",
            "name_short": "N-channel MOSFET IRLML2402TRPBF (SOT-23)",
        },
        {
            "taxonomy": ["transistor", "sot_23", "mosfet", "n_channel",
                         "enhancement_mode", "20_volt", "4_2_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irlml2502trpbf",
            "name_short": "N-channel MOSFET IRLML2502TRPBF (SOT-23)",
        },
        {
            "taxonomy": ["transistor", "sot_23", "mosfet", "n_channel",
                         "enhancement_mode", "30_volt", "1_2_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irlml2803trpbf",
            "name_short": "N-channel MOSFET IRLML2803TRPBF (SOT-23)",
        },
        # P-channel logic-level SOT-23 siblings.
        {
            "taxonomy": ["transistor", "sot_23", "mosfet", "p_channel",
                         "enhancement_mode", "30_volt", "760_milliamp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irlml5103trpbf",
            "name_short": "P-channel MOSFET IRLML5103TRPBF (SOT-23)",
        },
        {
            "taxonomy": ["transistor", "sot_23", "mosfet", "p_channel",
                         "enhancement_mode", "30_volt", "3_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irlml5203trpbf",
            "name_short": "P-channel MOSFET IRLML5203TRPBF (SOT-23)",
        },
        {
            "taxonomy": ["transistor", "sot_23", "mosfet", "p_channel",
                         "enhancement_mode", "20_volt", "3_7_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irlml6402trpbf",
            "name_short": "P-channel MOSFET IRLML6402TRPBF (SOT-23)",
        },
        # More DPAK, TO-247AC, TO-220AB and the first TO-263 (D2PAK) body.
        {
            "taxonomy": ["transistor", "to_252", "mosfet", "n_channel",
                         "enhancement_mode", "100_volt", "10_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irlr120ntrpbf",
            "name_short": "N-channel MOSFET IRLR120NTRPBF (DPAK)",
        },
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "n_channel",
                         "enhancement_mode", "500_volt", "20_amp"],
            "manufacturer": "vishay_intertech",
            "part_number": "irfp460pbf",
            "name_short": "N-channel MOSFET IRFP460PBF (TO-247AC-3)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "100_volt", "9_2_amp"],
            "manufacturer": "vishay_intertech",
            "part_number": "irf520pbf",
            "name_short": "N-channel MOSFET IRF520PBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "100_volt", "9_7_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irf520npbf",
            "name_short": "N-channel MOSFET IRF520NPBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "400_volt", "2_amp"],
            "manufacturer": "vishay_intertech",
            "part_number": "irf710pbf",
            "name_short": "N-channel MOSFET IRF710PBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "500_volt", "8_amp"],
            "manufacturer": "vishay_intertech",
            "part_number": "irf840apbf",
            "name_short": "N-channel MOSFET IRF840APBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_263", "mosfet", "n_channel",
                         "enhancement_mode", "500_volt", "8_amp"],
            "manufacturer": "vishay_intertech",
            "part_number": "irf840astrlpbf",
            "name_short": "N-channel MOSFET IRF840ASTRLPBF (TO-263 D2PAK)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "40_volt", "120_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irf1404zpbf",
            "name_short": "N-channel MOSFET IRF1404ZPBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "75_volt", "130_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irf1407pbf",
            "name_short": "N-channel MOSFET IRF1407PBF (TO-220AB)",
        },
        # Fifth MOSFET batch.  Page label D2PAK maps to the existing to_263
        # token (TO-263 and D2PAK are the same JEDEC outline).
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "40_volt", "270_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irf2804pbf",
            "name_short": "N-channel MOSFET IRF2804PBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "55_volt", "175_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irf2805pbf",
            "name_short": "N-channel MOSFET IRF2805PBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "55_volt", "110_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irf3205zpbf",
            "name_short": "N-channel MOSFET IRF3205ZPBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_263", "mosfet", "n_channel",
                         "enhancement_mode", "55_volt", "110_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irf3205strlpbf",
            "name_short": "N-channel MOSFET IRF3205STRLPBF (D2PAK)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "150_volt", "43_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irf3415pbf",
            "name_short": "N-channel MOSFET IRF3415PBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "n_channel",
                         "enhancement_mode", "150_volt", "43_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfp3415pbf",
            "name_short": "N-channel MOSFET IRFP3415PBF (TO-247AC)",
        },
        {
            "taxonomy": ["transistor", "to_263", "mosfet", "n_channel",
                         "enhancement_mode", "100_volt", "57_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irf3710strlpbf",
            "name_short": "N-channel MOSFET IRF3710STRLPBF (D2PAK)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "75_volt", "140_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irf3808pbf",
            "name_short": "N-channel MOSFET IRF3808PBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_263", "mosfet", "p_channel",
                         "enhancement_mode", "55_volt", "70_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irf4905strlpbf",
            "name_short": "P-channel MOSFET IRF4905STRLPBF (D2PAK)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "p_channel",
                         "enhancement_mode", "100_volt", "40_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irf5210pbf",
            "name_short": "P-channel MOSFET IRF5210PBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_263", "mosfet", "p_channel",
                         "enhancement_mode", "100_volt", "38_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irf5210strlpbf",
            "name_short": "P-channel MOSFET IRF5210STRLPBF (D2PAK)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "p_channel",
                         "enhancement_mode", "55_volt", "31_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irf5305pbf",
            "name_short": "P-channel MOSFET IRF5305PBF (TO-220AB)",
        },
        # Seventh MOSFET batch: high-voltage (800 V / 1 kV) and DPAK/D2PAK
        # bodies.  D2PAK and DPAK(TO-252AA) map to to_263 / to_252 tokens.
        {
            "taxonomy": ["transistor", "to_252", "mosfet", "p_channel",
                         "enhancement_mode", "55_volt", "31_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfr5305trpbf",
            "name_short": "P-channel MOSFET IRFR5305TRPBF (DPAK)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "p_channel",
                         "enhancement_mode", "200_volt", "6_5_amp"],
            "manufacturer": "vishay_intertech",
            "part_number": "irf9630pbf",
            "name_short": "P-channel MOSFET IRF9630PBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "p_channel",
                         "enhancement_mode", "200_volt", "11_amp"],
            "manufacturer": "vishay_intertech",
            "part_number": "irf9640pbf",
            "name_short": "P-channel MOSFET IRF9640PBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_263", "mosfet", "p_channel",
                         "enhancement_mode", "200_volt", "6_8_amp"],
            "manufacturer": "vishay_intertech",
            "part_number": "irf9640strlpbf",
            "name_short": "P-channel MOSFET IRF9640STRLPBF (TO-263 D2PAK)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "100_volt", "96_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfb4410pbf",
            "name_short": "N-channel MOSFET IRFB4410PBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "800_volt", "1_8_amp"],
            "manufacturer": "vishay_intertech",
            "part_number": "irfbe20pbf",
            "name_short": "N-channel MOSFET IRFBE20PBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220", "mosfet", "n_channel",
                         "enhancement_mode", "1000_volt", "3_1_amp"],
            "manufacturer": "vishay_intertech",
            "part_number": "irfbg30pbf",
            "name_short": "N-channel MOSFET IRFBG30PBF (TO-220)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "75_volt", "210_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfb3077pbf",
            "name_short": "N-channel MOSFET IRFB3077PBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "60_volt", "210_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfb3206pbf",
            "name_short": "N-channel MOSFET IRFB3206PBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "60_volt", "160_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfb3306pbf",
            "name_short": "N-channel MOSFET IRFB3306PBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "75_volt", "128_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfb3307zpbf",
            "name_short": "N-channel MOSFET IRFB3307ZPBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_263", "mosfet", "n_channel",
                         "enhancement_mode", "500_volt", "8_amp"],
            "manufacturer": "vishay_intertech",
            "part_number": "irf840strlpbf",
            "name_short": "N-channel MOSFET IRF840STRLPBF (TO-263 D2PAK)",
        },
        # Ninth MOSFET batch: IRFB series.  TO-220 / TO-220-3 page labels are
        # kept as printed; TO-220-3 is the JEDEC 3-lead TO-220 outline.
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "75_volt", "80_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfb3607pbf",
            "name_short": "N-channel MOSFET IRFB3607PBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "200_volt", "18_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfb4020pbf",
            "name_short": "N-channel MOSFET IRFB4020PBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220", "mosfet", "n_channel",
                         "enhancement_mode", "100_volt", "180_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfb4110pbf",
            "name_short": "N-channel MOSFET IRFB4110PBF (TO-220)",
        },
        {
            "taxonomy": ["transistor", "to_220", "mosfet", "n_channel",
                         "enhancement_mode", "150_volt", "104_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfb4115pbf",
            "name_short": "N-channel MOSFET IRFB4115PBF (TO-220)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "200_volt", "65_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfb4227pbf",
            "name_short": "N-channel MOSFET IRFB4227PBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "250_volt", "46_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfb4229pbf",
            "name_short": "N-channel MOSFET IRFB4229PBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220_3", "mosfet", "n_channel",
                         "enhancement_mode", "100_volt", "127_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfb4310zpbf",
            "name_short": "N-channel MOSFET IRFB4310ZPBF (TO-220-3)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "150_volt", "85_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfb4321pbf",
            "name_short": "N-channel MOSFET IRFB4321PBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "100_volt", "97_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfb4410zpbf",
            "name_short": "N-channel MOSFET IRFB4410ZPBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "100_volt", "73_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfb4610pbf",
            "name_short": "N-channel MOSFET IRFB4610PBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "100_volt", "75_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfb4710pbf",
            "name_short": "N-channel MOSFET IRFB4710PBF (TO-220AB)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "200_volt", "56_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfb260npbf",
            "name_short": "N-channel MOSFET IRFB260NPBF (TO-220AB)",
        },
        # Tenth MOSFET batch: IRFP TO-247AC series (the -3 page suffix is the
        # same 3-lead outline, one token covers both labels).
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "n_channel",
                         "enhancement_mode", "55_volt", "81_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfp054npbf",
            "name_short": "N-channel MOSFET IRFP054NPBF (TO-247AC)",
        },
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "n_channel",
                         "enhancement_mode", "100_volt", "33_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfp140npbf",
            "name_short": "N-channel MOSFET IRFP140NPBF (TO-247AC-3)",
        },
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "n_channel",
                         "enhancement_mode", "100_volt", "42_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfp150mpbf",
            "name_short": "N-channel MOSFET IRFP150MPBF (TO-247AC-3)",
        },
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "n_channel",
                         "enhancement_mode", "200_volt", "20_amp"],
            "manufacturer": "vishay_intertech",
            "part_number": "irfp240pbf",
            "name_short": "N-channel MOSFET IRFP240PBF (TO-247AC)",
        },
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "n_channel",
                         "enhancement_mode", "200_volt", "30_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfp250mpbf",
            "name_short": "N-channel MOSFET IRFP250MPBF (TO-247AC-3)",
        },
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "n_channel",
                         "enhancement_mode", "200_volt", "50_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfp260npbf",
            "name_short": "N-channel MOSFET IRFP260NPBF (TO-247AC-3)",
        },
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "n_channel",
                         "enhancement_mode", "200_volt", "50_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfp260mpbf",
            "name_short": "N-channel MOSFET IRFP260MPBF (TO-247AC)",
        },
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "n_channel",
                         "enhancement_mode", "400_volt", "16_amp"],
            "manufacturer": "vishay_intertech",
            "part_number": "irfp350pbf",
            "name_short": "N-channel MOSFET IRFP350PBF (TO-247AC)",
        },
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "n_channel",
                         "enhancement_mode", "500_volt", "8_7_amp"],
            "manufacturer": "vishay_intertech",
            "part_number": "irfp450pbf",
            "name_short": "N-channel MOSFET IRFP450PBF (TO-247AC-3)",
        },
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "n_channel",
                         "enhancement_mode", "500_volt", "14_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfp450lcpbf",
            "name_short": "N-channel MOSFET IRFP450LCPBF (TO-247AC-3)",
        },
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "p_channel",
                         "enhancement_mode", "100_volt", "23_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfp9140npbf",
            "name_short": "P-channel MOSFET IRFP9140NPBF (TO-247AC-3)",
        },
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "p_channel",
                         "enhancement_mode", "200_volt", "12_amp"],
            "manufacturer": "vishay_intertech",
            "part_number": "irfp9240pbf",
            "name_short": "P-channel MOSFET IRFP9240PBF (TO-247AC-3)",
        },
        # Eleventh MOSFET batch: more IRFP plus onsemi FQA bodies (TO-3PN is
        # the isolated TO-247-style outline, TO-3P-3 the non-isolated one).
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "n_channel",
                         "enhancement_mode", "60_volt", "200_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfp3206pbf",
            "name_short": "N-channel MOSFET IRFP3206PBF (TO-247AC)",
        },
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "n_channel",
                         "enhancement_mode", "100_volt", "57_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfp3710pbf",
            "name_short": "N-channel MOSFET IRFP3710PBF (TO-247AC)",
        },
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "n_channel",
                         "enhancement_mode", "100_volt", "180_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfp4110pbf",
            "name_short": "N-channel MOSFET IRFP4110PBF (TO-247AC)",
        },
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "n_channel",
                         "enhancement_mode", "200_volt", "65_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfp4227pbf",
            "name_short": "N-channel MOSFET IRFP4227PBF (TO-247AC)",
        },
        {
            "taxonomy": ["transistor", "to_3pn", "mosfet", "n_channel",
                         "enhancement_mode", "900_volt", "9_amp"],
            "manufacturer": "onsemi",
            "part_number": "fqa9n90c_f109",
            "name_short": "N-channel MOSFET FQA9N90C-F109 (TO-3PN)",
        },
        {
            "taxonomy": ["transistor", "to_3p_3", "mosfet", "n_channel",
                         "enhancement_mode", "500_volt", "28_4_amp"],
            "manufacturer": "onsemi",
            "part_number": "fqa28n50",
            "name_short": "N-channel MOSFET FQA28N50 (TO-3P-3)",
        },
        # First TO-204 (JEDEC TO-3) power BJTs and a Darlington.
        {
            "taxonomy": ["transistor", "to_204", "bipolar", "pnp",
                         "250_volt", "16_amp"],
            "manufacturer": "onsemi",
            "part_number": "mj15025g",
            "name_short": "PNP Transistor MJ15025G (TO-204)",
        },
        {
            "taxonomy": ["transistor", "to_204", "bipolar", "pnp",
                         "140_volt", "20_amp"],
            "manufacturer": "onsemi",
            "part_number": "mj15004g",
            "name_short": "PNP Transistor MJ15004G (TO-204)",
        },
        {
            "taxonomy": ["transistor", "to_204", "bipolar", "npn",
                         "250_volt", "16_amp"],
            "manufacturer": "onsemi",
            "part_number": "mj15024g",
            "name_short": "NPN Transistor MJ15024G (TO-204)",
        },
        {
            "taxonomy": ["transistor", "to_204", "bipolar", "npn", "darlington",
                         "120_volt", "50_amp"],
            "manufacturer": "onsemi",
            "part_number": "mj11032g",
            "name_short": "NPN Darlington Transistor MJ11032G (TO-204)",
        },
        # Twelfth MOSFET batch: high-current IRFP Z/N series.
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "n_channel",
                         "enhancement_mode", "100_volt", "134_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfp4310zpbf",
            "name_short": "N-channel MOSFET IRFP4310ZPBF (TO-247AC-3)",
        },
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "n_channel",
                         "enhancement_mode", "150_volt", "78_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfp4321pbf",
            "name_short": "N-channel MOSFET IRFP4321PBF (TO-247AC-3)",
        },
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "n_channel",
                         "enhancement_mode", "75_volt", "195_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfp4368pbf",
            "name_short": "N-channel MOSFET IRFP4368PBF (TO-247AC)",
        },
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "n_channel",
                         "enhancement_mode", "100_volt", "290_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfp4468pbf",
            "name_short": "N-channel MOSFET IRFP4468PBF (TO-247AC)",
        },
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "n_channel",
                         "enhancement_mode", "150_volt", "171_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfp4568pbf",
            "name_short": "N-channel MOSFET IRFP4568PBF (TO-247AC-3)",
        },
        # Thirteenth MOSFET batch: high-voltage 600V/900V/1kV TO-247AC parts
        # must never be silently replaced with lower-voltage siblings.
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "n_channel",
                         "enhancement_mode", "200_volt", "130_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfp4668pbf",
            "name_short": "N-channel MOSFET IRFP4668PBF (TO-247AC)",
        },
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "n_channel",
                         "enhancement_mode", "250_volt", "93_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfp4768pbf",
            "name_short": "N-channel MOSFET IRFP4768PBF (TO-247AC)",
        },
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "n_channel",
                         "enhancement_mode", "200_volt", "94_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfp90n20dpbf",
            "name_short": "N-channel MOSFET IRFP90N20DPBF (TO-247AC)",
        },
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "n_channel",
                         "enhancement_mode", "600_volt", "16_amp"],
            "manufacturer": "vishay_intertech",
            "part_number": "irfpc60lcpbf",
            "name_short": "N-channel MOSFET IRFPC60LCPBF (TO-247AC)",
        },
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "n_channel",
                         "enhancement_mode", "900_volt", "6_7_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfpf50pbf",
            "name_short": "N-channel MOSFET IRFPF50PBF (TO-247AC)",
        },
        {
            "taxonomy": ["transistor", "to_247ac", "mosfet", "n_channel",
                         "enhancement_mode", "1000_volt", "6_1_amp"],
            "manufacturer": "vishay_intertech",
            "part_number": "irfpg50pbf",
            "name_short": "N-channel MOSFET IRFPG50PBF (TO-247AC)",
        },
        # Fourteenth MOSFET batch: SO-8 power MOSFETs (page label SO-8; new
        # so_8 package token for the family) and more DPAK parts.
        {
            "taxonomy": ["transistor", "so_8", "mosfet", "p_channel",
                         "enhancement_mode", "20_volt", "6_7_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irf7404trpbf",
            "name_short": "P-channel MOSFET IRF7404TRPBF (SO-8)",
        },
        {
            "taxonomy": ["transistor", "so_8", "mosfet", "n_channel",
                         "enhancement_mode", "30_volt", "13_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irf7413trpbf",
            "name_short": "N-channel MOSFET IRF7413TRPBF (SO-8)",
        },
        {
            "taxonomy": ["transistor", "so_8", "mosfet", "p_channel",
                         "enhancement_mode", "30_volt", "10_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irf7416trpbf",
            "name_short": "P-channel MOSFET IRF7416TRPBF (SO-8)",
        },
        {
            "taxonomy": ["transistor", "so_8", "mosfet", "n_channel",
                         "enhancement_mode", "30_volt", "20_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irf7832trpbf",
            "name_short": "N-channel MOSFET IRF7832TRPBF (SO-8)",
        },
        {
            "taxonomy": ["transistor", "to_252", "mosfet", "n_channel",
                         "enhancement_mode", "600_volt", "1_9_amp"],
            "manufacturer": "onsemi",
            "part_number": "fqd2n60ctm",
            "name_short": "N-channel MOSFET FQD2N60CTM (DPAK)",
        },
        {
            "taxonomy": ["transistor", "to_252", "mosfet", "n_channel",
                         "enhancement_mode", "55_volt", "17_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irlr024ntrpbf",
            "name_short": "N-channel MOSFET IRLR024NTRPBF (DPAK)",
        },
        {
            "taxonomy": ["transistor", "to_252", "mosfet", "n_channel",
                         "enhancement_mode", "100_volt", "9_4_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfr120ntrpbf",
            "name_short": "N-channel MOSFET IRFR120NTRPBF (DPAK)",
        },
        {
            "taxonomy": ["transistor", "to_252", "mosfet", "n_channel",
                         "enhancement_mode", "400_volt", "3_1_amp"],
            "manufacturer": "vishay_intertech",
            "part_number": "irfr320trpbf",
            "name_short": "N-channel MOSFET IRFR320TRPbF (DPAK)",
        },
        {
            "taxonomy": ["transistor", "to_252", "mosfet", "n_channel",
                         "enhancement_mode", "55_volt", "42_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irlr2905trpbf",
            "name_short": "N-channel MOSFET IRLR2905TRPBF (DPAK)",
        },
        # Fifteenth MOSFET batch: more DPAK plus the first TO-251 (IPAK)
        # through-tab bodies.
        {
            "taxonomy": ["transistor", "to_252", "mosfet", "n_channel",
                         "enhancement_mode", "500_volt", "5_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfr430atrpbf",
            "name_short": "N-channel MOSFET IRFR430ATRPBF (DPAK)",
        },
        {
            "taxonomy": ["transistor", "to_252", "mosfet", "n_channel",
                         "enhancement_mode", "100_volt", "31_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfr3410trpbf",
            "name_short": "N-channel MOSFET IRFR3410TRPBF (DPAK)",
        },
        {
            "taxonomy": ["transistor", "to_252", "mosfet", "n_channel",
                         "enhancement_mode", "100_volt", "17_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irlr3410trpbf",
            "name_short": "N-channel MOSFET IRLR3410TRPBF (DPAK)",
        },
        {
            "taxonomy": ["transistor", "to_252", "mosfet", "p_channel",
                         "enhancement_mode", "100_volt", "13_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfr5410trpbf",
            "name_short": "P-channel MOSFET IRFR5410TRPBF (DPAK)",
        },
        {
            "taxonomy": ["transistor", "to_252", "mosfet", "p_channel",
                         "enhancement_mode", "100_volt", "6_6_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfr9120ntrpbf",
            "name_short": "P-channel MOSFET IRFR9120NTRPBF (DPAK)",
        },
        {
            "taxonomy": ["transistor", "to_252", "mosfet", "p_channel",
                         "enhancement_mode", "200_volt", "3_6_amp"],
            "manufacturer": "vishay_intertech",
            "part_number": "irfr9220trpbf",
            "name_short": "P-channel MOSFET IRFR9220TRPBF (DPAK)",
        },
        {
            "taxonomy": ["transistor", "to_252", "mosfet", "n_channel",
                         "enhancement_mode", "600_volt", "2_amp"],
            "manufacturer": "vishay_intertech",
            "part_number": "irfrc20trlpbf",
            "name_short": "N-channel MOSFET IRFRC20TRLPBF (DPAK)",
        },
        {
            "taxonomy": ["transistor", "to_251", "mosfet", "n_channel",
                         "enhancement_mode", "55_volt", "17_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irlu024npbf",
            "name_short": "N-channel MOSFET IRLU024NPBF (TO-251 IPAK)",
        },
        {
            "taxonomy": ["transistor", "to_251", "mosfet", "n_channel",
                         "enhancement_mode", "100_volt", "9_4_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfu120npbf",
            "name_short": "N-channel MOSFET IRFU120NPBF (TO-251 IPAK)",
        },
        {
            "taxonomy": ["transistor", "to_251", "mosfet", "n_channel",
                         "enhancement_mode", "200_volt", "5_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfu220npbf",
            "name_short": "N-channel MOSFET IRFU220NPBF (TO-251 IPAK)",
        },
        {
            "taxonomy": ["transistor", "to_251", "mosfet", "n_channel",
                         "enhancement_mode", "100_volt", "16_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfu3910pbf",
            "name_short": "N-channel MOSFET IRFU3910PBF (TO-251 IPAK)",
        },
        {
            "taxonomy": ["transistor", "to_251", "mosfet", "p_channel",
                         "enhancement_mode", "100_volt", "13_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irfu5410pbf",
            "name_short": "P-channel MOSFET IRFU5410PBF (TO-251 IPAK)",
        },
        # Sixteenth MOSFET batch: one more IPAK, the first SOT-223 power
        # body, a second-source IRF830A, and a logic-level SOT-23 P-channel.
        {
            "taxonomy": ["transistor", "to_251", "mosfet", "p_channel",
                         "enhancement_mode", "60_volt", "8_8_amp"],
            "manufacturer": "vishay_intertech",
            "part_number": "irfu9024pbf",
            "name_short": "P-channel MOSFET IRFU9024PBF (TO-251 IPAK)",
        },
        {
            "taxonomy": ["transistor", "sot_23", "mosfet", "p_channel",
                         "enhancement_mode", "12_volt", "4_3_amp"],
            "manufacturer": "infineon_technologies",
            "part_number": "irlml6401trpbf",
            "name_short": "P-channel MOSFET IRLML6401TRPBF (SOT-23)",
        },
        {
            "taxonomy": ["transistor", "sot_223", "mosfet", "p_channel",
                         "enhancement_mode", "60_volt", "1_8_amp"],
            "manufacturer": "vishay_intertech",
            "part_number": "irfl9014trpbf",
            "name_short": "P-channel MOSFET IRFL9014TRPBF (SOT-223)",
        },
        {
            "taxonomy": ["transistor", "to_220ab", "mosfet", "n_channel",
                         "enhancement_mode", "500_volt", "5_amp"],
            "manufacturer": "vishay_intertech",
            "part_number": "irf830apbf",
            "name_short": "N-channel MOSFET IRF830APBF (TO-220AB)",
        },
        # MJD power pairs: the DPAK PNP and the first bipolar IPAK bodies
        # (MJD44H11 is the NPN sibling, MJD45H11 the PNP one).
        {
            "taxonomy": ["transistor", "to_252", "bipolar", "pnp",
                         "80_volt", "8_amp"],
            "manufacturer": "onsemi",
            "part_number": "mjd45h11g",
            "name_short": "PNP Transistor MJD45H11G (DPAK)",
        },
        {
            "taxonomy": ["transistor", "to_251", "bipolar", "npn",
                         "80_volt", "8_amp"],
            "manufacturer": "onsemi",
            "part_number": "mjd44h11_1g",
            "name_short": "NPN Transistor MJD44H11-1G (TO-251 IPAK)",
        },
        {
            "taxonomy": ["transistor", "to_251", "bipolar", "pnp",
                         "80_volt", "8_amp"],
            "manufacturer": "onsemi",
            "part_number": "mjd45h11_1g",
            "name_short": "PNP Transistor MJD45H11-1G (TO-251 IPAK)",
        },
        # APEC power FETs: single P-channel in SO-8 and the first dual-FET
        # SO-8 row (the dual token sits after enhancement_mode).
        {
            "taxonomy": ["transistor", "so_8", "mosfet", "p_channel",
                         "enhancement_mode", "30_volt", "9_amp"],
            "manufacturer": "apec_advanced_power_elec",
            "part_number": "ap4435gm",
            "name_short": "P-channel MOSFET AP4435GM (SO-8)",
        },
        {
            "taxonomy": ["transistor", "so_8", "mosfet", "p_channel",
                         "enhancement_mode", "dual", "30_volt", "5_amp"],
            "manufacturer": "apec_advanced_power_elec",
            "part_number": "ap4953gm",
            "name_short": "Dual P-channel MOSFET AP4953GM (SO-8)",
        },
        {
            "taxonomy": ["transistor", "so_8", "mosfet", "p_channel",
                         "enhancement_mode", "dual", "30_volt", "6_9_amp"],
            "manufacturer": "onsemi",
            "part_number": "fds4935bz",
            "name_short": "Dual P-channel MOSFET FDS4935BZ (SO-8)",
        },
        {
            "taxonomy": ["transistor", "sot_23", "mosfet", "p_channel",
                         "enhancement_mode", "30_volt", "4_amp"],
            "manufacturer": "vishay_intertech",
            "part_number": "si2343cds_t1_ge3",
            "name_short": "P-channel MOSFET SI2343CDS-T1-GE3 (SOT-23)",
        },
    ]

    for transistor in transistors:
        option = {}
        taxonomy = transistor["taxonomy"]
        for taxonomy_index in range(len(taxonomy)):
            option[f"taxonomy_{taxonomy_index + 2}"] = taxonomy[taxonomy_index]
        option["taxonomy_14"] = transistor["manufacturer"]
        option["taxonomy_15"] = transistor["part_number"]
        option["name_short"] = transistor["name_short"]
        if "name_readable_override" in transistor:
            option["name_readable_override"] = transistor["name_readable_override"]
        options.append(option)


if __name__ == "__main__":
    main()
