def main(**kwargs):
    options = kwargs.get("options", [])

    # Keep exact diode definitions as a plain array.  Diode families do not
    # share every package/manufacturer combination, so a cross-product of four
    # separate lists would create invalid parts that do not exist.
    diodes = [
        {
            "diode_type": "rectifier",
            "package": "sma",
            "manufacturer": "",
            "part_number": "m4",
            "name_short": "Rectifier Diode M4 (SMA)",
        },
        {
            "diode_type": "bridge_rectifier",
            "package": "mbs",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "mb10s_50mil",
            "name_short": "Single-Phase Bridge Rectifier MB10S-50MIL (MBS)",
        },
        {
            "diode_type": "rectifier",
            "package": "sod_123fl",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "sm4007pl",
            "name_short": "Rectifier Diode SM4007PL (SOD-123FL)",
        },
        {
            "diode_type": "rectifier",
            "package": "sma",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "m7",
            "name_short": "Rectifier Diode M7 (SMA)",
        },
        {
            "diode_type": "fast_recovery",
            "package": "sma",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "us1m",
            "name_short": "Fast-Recovery Diode US1M (SMA)",
        },
        # Through-hole general-purpose rectifiers and fast-recovery diodes
        # (MDD DO-41 / DO-201AD / DO-15 / R-6 bodies).
        {
            "diode_type": "rectifier",
            "package": "do_41",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "1n4001",
            "name_short": "Rectifier Diode 1N4001 (DO-41)",
        },
        {
            "diode_type": "rectifier",
            "package": "do_41",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "1n4007g",
            "name_short": "Rectifier Diode 1N4007G (DO-41)",
        },
        {
            "diode_type": "rectifier",
            "package": "do_201ad",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "1n5401",
            "name_short": "Rectifier Diode 1N5401 (DO-201AD)",
        },
        {
            "diode_type": "rectifier",
            "package": "do_201ad",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "1n5408",
            "name_short": "Rectifier Diode 1N5408 (DO-201AD)",
        },
        {
            "diode_type": "rectifier",
            "package": "r_6",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "6a10",
            "name_short": "Rectifier Diode 6A10 (R-6)",
        },
        {
            "diode_type": "rectifier",
            "package": "r_6",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "10a10",
            "name_short": "Rectifier Diode 10A10 (R-6)",
        },
        {
            "diode_type": "fast_recovery",
            "package": "do_41",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "fr104",
            "name_short": "Fast-Recovery Diode FR104 (DO-41)",
        },
        {
            "diode_type": "fast_recovery",
            "package": "do_41",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "fr107",
            "name_short": "Fast-Recovery Diode FR107 (DO-41)",
        },
        {
            "diode_type": "fast_recovery",
            "package": "do_15",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "fr157",
            "name_short": "Fast-Recovery Diode FR157 (DO-15)",
        },
        {
            "diode_type": "fast_recovery",
            "package": "do_15",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "fr207",
            "name_short": "Fast-Recovery Diode FR207 (DO-15)",
        },
        {
            "diode_type": "fast_recovery",
            "package": "do_201ad",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "fr307",
            "name_short": "Fast-Recovery Diode FR307 (DO-201AD)",
        },
        # High-efficiency / super-fast through-hole rectifiers.
        {
            "diode_type": "fast_recovery",
            "package": "do_41",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "her107",
            "name_short": "High-Efficiency Rectifier HER107 (DO-41)",
        },
        {
            "diode_type": "fast_recovery",
            "package": "do_201ad",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "her307",
            "name_short": "High-Efficiency Rectifier HER307 (DO-201AD)",
        },
        # HER204/HER205: DO-15 fast-recovery siblings of the HER107/HER307.
        {
            "diode_type": "fast_recovery",
            "package": "do_15",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "her204",
            "name_short": "High-Efficiency Rectifier HER204 (DO-15)",
        },
        {
            "diode_type": "fast_recovery",
            "package": "do_15",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "her205",
            "name_short": "High-Efficiency Rectifier HER205 (DO-15)",
        },
        # HER303, RL207, SF28/SF36: more DO-15 / DO-201AD rectifier bodies.
        {
            "diode_type": "fast_recovery",
            "package": "do_201ad",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "her303",
            "name_short": "High-Efficiency Rectifier HER303 (DO-201AD)",
        },
        {
            "diode_type": "rectifier",
            "package": "do_15",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "rl207",
            "name_short": "Rectifier Diode RL207 (DO-15)",
        },
        {
            "diode_type": "fast_recovery",
            "package": "do_15",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "sf28_tape",
            "name_short": "Super-Fast Recovery Diode SF28 Tape (DO-15)",
        },
        {
            "diode_type": "fast_recovery",
            "package": "do_201ad",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "sf36",
            "name_short": "Super-Fast Recovery Diode SF36 (DO-201AD)",
        },
        # KBL406/KBL608/KBP210: second values on the existing kbl/kbp bodies.
        {
            "diode_type": "bridge_rectifier",
            "package": "kbl",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "kbl406",
            "name_short": "Single-Phase Bridge Rectifier KBL406 (KBL)",
        },
        {
            "diode_type": "bridge_rectifier",
            "package": "kbl",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "kbl608",
            "name_short": "Single-Phase Bridge Rectifier KBL608 (KBL)",
        },
        {
            "diode_type": "bridge_rectifier",
            "package": "kbp",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "kbp210",
            "name_short": "Single-Phase Bridge Rectifier KBP210 (KBP)",
        },
        # KBPC metal-case, BR-6, and KBU bridge bodies (all new tokens).
        {
            "diode_type": "bridge_rectifier",
            "package": "kbpc_8",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "kbpc1010",
            "name_short": "Single-Phase Bridge Rectifier KBPC1010 (KBPC-8)",
        },
        {
            "diode_type": "bridge_rectifier",
            "package": "kbpc_25",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "kbpc5010",
            "name_short": "Single-Phase Bridge Rectifier KBPC5010 (KBPC-25)",
        },
        {
            "diode_type": "bridge_rectifier",
            "package": "br_6",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "kbpc608",
            "name_short": "Single-Phase Bridge Rectifier KBPC608 (BR-6)",
        },
        {
            "diode_type": "bridge_rectifier",
            "package": "br_6",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "kbpc610",
            "name_short": "Single-Phase Bridge Rectifier KBPC610 (BR-6)",
        },
        {
            "diode_type": "bridge_rectifier",
            "package": "kbu",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "kbu808",
            "name_short": "Single-Phase Bridge Rectifier KBU808 (KBU)",
        },
        # W06 mini DIP-4 bridge and SR540 DO-201AD Schottky.
        {
            "diode_type": "bridge_rectifier",
            "package": "dip_4",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "w06",
            "name_short": "Single-Phase Bridge Rectifier W06 (DIP-4)",
        },
        {
            "diode_type": "schottky",
            "package": "do_201ad",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "sr540",
            "name_short": "Schottky Diode SR540 (DO-201AD)",
        },
        # DB107S DBS-body bridge, ES2J/ES2JB SMB fast recovery, RS1M SMA.
        {
            "diode_type": "bridge_rectifier",
            "package": "dbs",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "db107s",
            "name_short": "Single-Phase Bridge Rectifier DB107S (DBS)",
        },
        {
            "diode_type": "fast_recovery",
            "package": "smb",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "es2jb",
            "name_short": "Fast-Recovery Diode ES2JB (SMB)",
        },
        {
            "diode_type": "fast_recovery",
            "package": "sma",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "rs1m",
            "name_short": "Fast-Recovery Diode RS1M (SMA)",
        },
        {
            "diode_type": "fast_recovery",
            "package": "sma",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "es2j",
            "name_short": "Fast-Recovery Diode ES2J (SMA)",
        },
        # R-1 axial rectifier and further 1N4xxx/1N54xxx values.
        {
            "diode_type": "rectifier",
            "package": "r_1",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "1a7g",
            "name_short": "Rectifier Diode 1A7G (R-1)",
        },
        {
            "diode_type": "rectifier",
            "package": "do_41",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "1n4004",
            "name_short": "Rectifier Diode 1N4004 (DO-41)",
        },
        {
            "diode_type": "rectifier",
            "package": "do_201ad",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "1n5404",
            "name_short": "Rectifier Diode 1N5404 (DO-201AD)",
        },
        # WOM and GBU bridge bodies beside the existing MBx/DB/KBP/KBL.
        {
            "diode_type": "bridge_rectifier",
            "package": "wom",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "2w10",
            "name_short": "Single-Phase Bridge Rectifier 2W10 (WOM)",
        },
        {
            "diode_type": "bridge_rectifier",
            "package": "gbu",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "gbu808",
            "name_short": "Single-Phase Bridge Rectifier GBU808 (GBU)",
        },
        # Vishay TO-247S dual common-cathode power Schottky (first diode row
        # outside MDD in this exact-power block).
        {
            "diode_type": "schottky_dual_common_cathode",
            "package": "to_247s",
            "manufacturer": "vishay_intertech",
            "part_number": "vs_mbr6045wt_n3",
            "name_short": "Dual Schottky Diode VS-MBR6045WT-N3 (TO-247S)",
        },
        {
            "diode_type": "fast_recovery",
            "package": "do_41",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "sf18",
            "name_short": "Super-Fast Recovery Diode SF18 (DO-41)",
        },
        # High-voltage general-purpose rectifier.
        {
            "diode_type": "rectifier",
            "package": "do_41",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "r3000",
            "name_short": "High-Voltage Rectifier R3000 (DO-41)",
        },
        # Through-hole Schottky rectifiers.
        {
            "diode_type": "schottky",
            "package": "do_41",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "1n5819",
            "name_short": "Schottky Diode 1N5819 (DO-41)",
        },
        {
            "diode_type": "schottky",
            "package": "do_41",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "sr160",
            "name_short": "Schottky Diode SR160 (DO-41)",
        },
        {
            "diode_type": "schottky",
            "package": "do_201ad",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "1n5822",
            "name_short": "Schottky Diode 1N5822 (DO-201AD)",
        },
        {
            "diode_type": "schottky",
            "package": "do_201ad",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "sr360",
            "name_short": "Schottky Diode SR360 (DO-201AD)",
        },
        # SMA Schottky rectifiers.
        {
            "diode_type": "schottky",
            "package": "sma",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "ss12",
            "name_short": "Schottky Diode SS12 (SMA)",
        },
        {
            "diode_type": "schottky",
            "package": "sma",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "ss16",
            "name_short": "Schottky Diode SS16 (SMA)",
        },
        {
            "diode_type": "schottky",
            "package": "sma",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "ss110",
            "name_short": "Schottky Diode SS110 (SMA)",
        },
        # 0.5 A MBS bridge beside the existing MB10S-50MIL.
        {
            "diode_type": "bridge_rectifier",
            "package": "mbs",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "mb6s_50mil",
            "name_short": "Single-Phase Bridge Rectifier MB6S-50MIL (MBS)",
        },
        {
            "diode_type": "schottky",
            "package": "sma",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "ss14",
            "name_short": "Schottky Diode SS14 (SMA)",
        },
        {
            "diode_type": "schottky",
            "package": "sod_123",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "b5819w_sl",
            "name_short": "Schottky Diode B5819W SL (SOD-123)",
        },
        {
            "diode_type": "schottky",
            "package": "sma",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "ss34",
            "name_short": "Schottky Diode SS34 (SMA)",
        },
        {
            "diode_type": "schottky",
            "package": "sma",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "ss210",
            "name_short": "Schottky Diode SS210 (SMA)",
        },
        {
            "diode_type": "schottky",
            "package": "sma",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "ss54",
            "name_short": "Schottky Diode SS54 (SMA)",
        },
        {
            "diode_type": "schottky",
            "package": "sod_323",
            "manufacturer": "guangdong_hottech",
            "part_number": "1n5819ws",
            "name_short": "Schottky Diode 1N5819WS (SOD-323)",
        },
        {
            "diode_type": "schottky",
            "package": "0402",
            "manufacturer": "",
            "part_number": "",
            "name_short": "Schottky Diode 0402 (generic)",
        },
        {"diode_type": "tvs_array", "package": "sot_143", "manufacturer": "littelfuse",
         "part_number": "sp0503bahtg", "name_short": "ESD Array SP0503BAHTG"},
        {
            "diode_type": "tvs_array",
            "package": "sot_23_6",
            "manufacturer": "protek",
            "part_number": "srv054pt7",
        },
        {
            "diode_type": "tvs_array",
            "package": "sot_23",
            "manufacturer": "protek",
            "part_number": "psm712_lf_t7",
            "name_short": "RS-485 TVS Array PSM712-LF-T7",
        },
        # C6650: ST five-line unidirectional ESD array in the SOT-23-6 body.
        {
            "diode_type": "tvs_array",
            "package": "sot_23_6",
            "manufacturer": "stmicroelectronics",
            "part_number": "esda6v1_5sc6",
            "name_short": "ESD Array ESDA6V1-5SC6",
        },
        {
            "diode_type": "switching",
            "package": "sod_523f",
            "manufacturer": "onsemi",
            "part_number": "1n4148wt",
            "name_short": "Switching Diode 1N4148WT",
        },
        {
            "diode_type": "switching",
            "package": "sod_323",
            "manufacturer": "onsemi",
            "part_number": "1n4148ws",
            "name_short": "Switching Diode 1N4148WS",
        },
        {
            "diode_type": "switching",
            "package": "sod_123",
            "manufacturer": "onsemi",
            "part_number": "1n4148w",
            "name_short": "Switching Diode 1N4148W",
        },
        {
            "diode_type": "switching",
            "package": "sod_123",
            "manufacturer": "st_semtech",
            "part_number": "1n4148w",
            "name_short": "Switching Diode 1N4148W",
        },
        {
            "diode_type": "switching",
            "package": "sod_123",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "1n4148w",
            "name_short": "Switching Diode 1N4148W (Jiangsu Changjing)",
        },
        {
            "diode_type": "switching_dual_series",
            "package": "sot_23",
            "manufacturer": "nexperia",
            "part_number": "bav99_215",
            "name_short": "Dual Switching Diode BAV99,215 (SOT-23)",
        },
        {
            "diode_type": "switching_dual_common_cathode",
            "package": "sot_23",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "bav70",
            "name_short": "Dual Switching Diode BAV70 (SOT-23)",
        },
        # Nexperia's exact BAV70 ordering code (100V/215mA, 4ns).
        {
            "diode_type": "switching_dual_common_cathode",
            "package": "sot_23",
            "manufacturer": "nexperia",
            "part_number": "bav70_215",
            "name_short": "Dual Switching Diode BAV70,215 (SOT-23)",
        },
        # Bridge-rectifier body families from MDD: MBF, DB, KBP, KBL.
        {
            "diode_type": "bridge_rectifier",
            "package": "mbf",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "mb10f_50mil",
            "name_short": "Single-Phase Bridge Rectifier MB10F-50MIL (MBF)",
        },
        {
            "diode_type": "bridge_rectifier",
            "package": "db",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "db107",
            "name_short": "Single-Phase Bridge Rectifier DB107 (DB)",
        },
        {
            "diode_type": "bridge_rectifier",
            "package": "kbp",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "kbp206",
            "name_short": "Single-Phase Bridge Rectifier KBP206 (KBP)",
        },
        {
            "diode_type": "bridge_rectifier",
            "package": "kbp",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "kbp310",
            "name_short": "Single-Phase Bridge Rectifier KBP310 (KBP)",
        },
        {
            "diode_type": "bridge_rectifier",
            "package": "kbl",
            "manufacturer": "mdd_microdiode_semiconductor",
            "part_number": "kbl410",
            "name_short": "Single-Phase Bridge Rectifier KBL410 (KBL)",
        },
        # Bidirectional trigger device: ST DB4 DIAC in DO-35.
        {
            "diode_type": "diac",
            "package": "do_35",
            "manufacturer": "stmicroelectronics",
            "part_number": "db4",
            "name_short": "Trigger Diac DB4 (DO-35)",
        },
        # Through-hole 500 mW zeners: BZX55 series in DO-35.
        {
            "diode_type": "zener",
            "package": "do_35",
            "manufacturer": "st_semtech",
            "part_number": "bzx55c2v4",
            "name_short": "Zener Diode BZX55C2V4 (DO-35)",
        },
        {
            "diode_type": "zener",
            "package": "do_35",
            "manufacturer": "st_semtech",
            "part_number": "bzx55c3v6",
            "name_short": "Zener Diode BZX55C3V6 (DO-35)",
        },
        {
            "diode_type": "zener",
            "package": "do_35",
            "manufacturer": "st_semtech",
            "part_number": "bzx55c3v9",
            "name_short": "Zener Diode BZX55C3V9 (DO-35)",
        },
        {
            "diode_type": "zener",
            "package": "do_35",
            "manufacturer": "st_semtech",
            "part_number": "bzx55c6v2",
            "name_short": "Zener Diode BZX55C6V2 (DO-35)",
        },
        {
            "diode_type": "zener",
            "package": "do_35",
            "manufacturer": "st_semtech",
            "part_number": "bzx55c6v8",
            "name_short": "Zener Diode BZX55C6V8 (DO-35)",
        },
        # BZX55 DO-35 series continued.
        {
            "diode_type": "zener",
            "package": "do_35",
            "manufacturer": "st_semtech",
            "part_number": "bzx55c7v5",
            "name_short": "Zener Diode BZX55C7V5 (DO-35)",
        },
        {
            "diode_type": "zener",
            "package": "do_35",
            "manufacturer": "st_semtech",
            "part_number": "bzx55c9v1",
            "name_short": "Zener Diode BZX55C9V1 (DO-35)",
        },
        {
            "diode_type": "zener",
            "package": "do_35",
            "manufacturer": "st_semtech",
            "part_number": "bzx55c13",
            "name_short": "Zener Diode BZX55C13 (DO-35)",
        },
        {
            "diode_type": "zener",
            "package": "do_35",
            "manufacturer": "st_semtech",
            "part_number": "bzx55c18",
            "name_short": "Zener Diode BZX55C18 (DO-35)",
        },
        {
            "diode_type": "zener",
            "package": "do_35",
            "manufacturer": "st_semtech",
            "part_number": "bzx55c24",
            "name_short": "Zener Diode BZX55C24 (DO-35)",
        },
        # 1 W DO-41 zeners: 1N47xxA series.
        {
            "diode_type": "zener",
            "package": "do_41",
            "manufacturer": "st_semtech",
            "part_number": "1n4731a",
            "name_short": "Zener Diode 1N4731A (DO-41)",
        },
        {
            "diode_type": "zener",
            "package": "do_41",
            "manufacturer": "st_semtech",
            "part_number": "1n4732a",
            "name_short": "Zener Diode 1N4732A (DO-41)",
        },
        {
            "diode_type": "zener",
            "package": "do_41",
            "manufacturer": "st_semtech",
            "part_number": "1n4735a",
            "name_short": "Zener Diode 1N4735A (DO-41)",
        },
        {
            "diode_type": "zener",
            "package": "do_41",
            "manufacturer": "st_semtech",
            "part_number": "1n4742a",
            "name_short": "Zener Diode 1N4742A (DO-41)",
        },
        {
            "diode_type": "zener",
            "package": "do_41",
            "manufacturer": "st_semtech",
            "part_number": "1n4752a",
            "name_short": "Zener Diode 1N4752A (DO-41)",
        },
        {
            "diode_type": "zener",
            "package": "do_41",
            "manufacturer": "st_semtech",
            "part_number": "1n4753a",
            "name_short": "Zener Diode 1N4753A (DO-41)",
        },
        # 5 W DO-27 power zeners: onsemi 1N533x/1N5350 series.
        {
            "diode_type": "zener",
            "package": "do_27",
            "manufacturer": "onsemi",
            "part_number": "1n5339brlg",
            "name_short": "5W Zener Diode 1N5339BRLG 5.6V (DO-27)",
        },
        {
            "diode_type": "zener",
            "package": "do_27",
            "manufacturer": "onsemi",
            "part_number": "1n5338brlg",
            "name_short": "5W Zener Diode 1N5338BRLG 5.1V (DO-27)",
        },
        {
            "diode_type": "zener",
            "package": "do_27",
            "manufacturer": "onsemi",
            "part_number": "1n5350brlg",
            "name_short": "5W Zener Diode 1N5350BRLG 13V (DO-27)",
        },
        {
            "diode_type": "schottky_dual_common_cathode",
            "package": "sot_523",
            "manufacturer": "diodes_incorporated",
            "part_number": "bas40t_05",
            "name_short": "Dual Schottky Diode BAS40T-05",
        },
        {
            "diode_type": "schottky",
            "package": "sod_123",
            "part_number": "ss14",
            "name_short": "Schottky Diode SOD-123",
        },
        {
            "diode_type": "schottky",
            "package": "sod_323",
            "part_number": "bat54w",
            "name_short": "Schottky Diode SOD-323",
        },
        {
            "diode_type": "schottky",
            "package": "sod_523",
            "part_number": "1ss400",
            "name_short": "Schottky Diode SOD-523",
        },
        # SparkFun-specific diodes/protection
        {
            "diode_type": "tvs",
            "package": "sot_353",
            "manufacturer": "toshiba",
            "part_number": "df5a5_6lfu",
            "name_short": "TVS Diode DF5A5.6LFU",
        },
        {
            "diode_type": "tvs",
            "package": "smb",
            "manufacturer": "brightking",
            "part_number": "p6smb6_8ca_tr13",
            "name_short": "Bidirectional TVS Diode P6SMB6.8CA/TR13",
        },
        {
            "diode_type": "tvs",
            "package": "smb",
            "manufacturer": "hongjiacheng",
            "part_number": "smbj6_5ca",
            "name_short": "Bidirectional TVS Diode SMBJ6.5CA",
        },
        {
            "diode_type": "esd",
            "package": "0402",
            "manufacturer": "littelfuse",
            "part_number": "pesd0402",
            "name_short": "ESD Suppressor PESD0402",
        },
        {
            "diode_type": "esd_array",
            "package": "sot_353",
            "manufacturer": "nexperia",
            "part_number": "pesd3v3l4ug",
            "name_short": "ESD Array PESD3V3L4UG",
        },
        {
            "diode_type": "tvs_array",
            "package": "sot_26",
            "manufacturer": "diodes_incorporated",
            "part_number": "dt1042_04so",
            "name_short": "TVS Array DT1042-04SO",
        },
        {
            "diode_type": "schottky",
            "package": "sod_323",
            "manufacturer": "infineon",
            "part_number": "bat60a",
            "name_short": "Schottky Diode BAT60A",
        },
        {
            "diode_type": "tvs_array",
            "package": "sot_143",
            "manufacturer": "nxp",
            "part_number": "prtr5v0u2x",
            "name_short": "USB ESD Protection PRTR5V0U2X",
        },
        {
            "diode_type": "schottky",
            "package": "sod_323",
            "manufacturer": "infineon",
            "part_number": "bat20j",
            "name_short": "Schottky Diode BAT20J",
        },
        {
            "diode_type": "schottky",
            "package": "sod_323",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "1ss404",
            "name_short": "Schottky Diode 1SS404 (SOD-323)",
        },
        {
            "diode_type": "schottky",
            "package": "sod_123",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "b0530w",
            "name_short": "Schottky Diode B0530W (SOD-123)",
        },
        {
            "diode_type": "zener",
            "package": "sod_123",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "bzt52c10",
            "name_short": "Zener Diode BZT52C10 10V (SOD-123)",
        },
        {
            "diode_type": "zener",
            "package": "sod_123",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "bzt52c15",
            "name_short": "Zener Diode BZT52C15 15V (SOD-123)",
        },
        {
            "diode_type": "zener",
            "package": "sod_123",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "bzt52c16",
            "name_short": "Zener Diode BZT52C16 16V (SOD-123)",
        },
        {
            "diode_type": "zener",
            "package": "sod_323",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "bzt52c18s",
            "name_short": "Zener Diode BZT52C18S 18V (SOD-323)",
        },
        {
            "diode_type": "zener",
            "package": "sod_123",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "bzt52c20",
            "name_short": "Zener Diode BZT52C20 20V (SOD-123)",
        },
        {
            "diode_type": "zener",
            "package": "sod_123",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "bzt52c22",
            "name_short": "Zener Diode BZT52C22 22V (SOD-123)",
        },
        {
            "diode_type": "zener",
            "package": "sod_123",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "bzt52c24",
            "name_short": "Zener Diode BZT52C24 24V (SOD-123)",
        },
        {
            "diode_type": "zener",
            "package": "sod_123",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "bzt52c33",
            "name_short": "Zener Diode BZT52C33 33V (SOD-123)",
        },
        {
            "diode_type": "zener",
            "package": "sod_123",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "bzt52c39",
            "name_short": "Zener Diode BZT52C39 39V (SOD-123)",
        },
        {
            "diode_type": "zener",
            "package": "sod_123",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "bzt52c3v3",
            "name_short": "Zener Diode BZT52C3V3 3.3V (SOD-123)",
        },
        {
            "diode_type": "zener",
            "package": "sod_123",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "bzt52c3v6",
            "name_short": "Zener Diode BZT52C3V6 3.6V (SOD-123)",
        },
        {
            "diode_type": "zener",
            "package": "sod_123",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "bzt52c3v9",
            "name_short": "Zener Diode BZT52C3V9 3.9V (SOD-123)",
        },
        {
            "diode_type": "zener",
            "package": "sod_123",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "bzt52c4v3",
            "name_short": "Zener Diode BZT52C4V3 4.3V (SOD-123)",
        },
        {
            "diode_type": "zener",
            "package": "sod_123",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "bzt52c4v7",
            "name_short": "Zener Diode BZT52C4V7 4.7V (SOD-123)",
        },
        {
            "diode_type": "zener",
            "package": "sod_123",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "bzt52c5v1",
            "name_short": "Zener Diode BZT52C5V1 5.1V (SOD-123)",
        },
        {
            "diode_type": "zener",
            "package": "sod_323",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "bzt52c5v1s_w8",
            "name_short": "Zener Diode BZT52C5V1S 5.1V (SOD-323)",
        },
        {
            "diode_type": "zener",
            "package": "sod_123",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "bzt52c5v6",
            "name_short": "Zener Diode BZT52C5V6 5.6V (SOD-123)",
        },
        {
            "diode_type": "zener",
            "package": "sod_123",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "bzt52c6v8",
            "name_short": "Zener Diode BZT52C6V8 6.8V (SOD-123)",
        },
        {
            "diode_type": "zener",
            "package": "sod_123",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "bzt52c7v5",
            "name_short": "Zener Diode BZT52C7V5 7.5V (SOD-123)",
        },
        {
            "diode_type": "zener",
            "package": "sod_123",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "bzt52c8v2_wd",
            "name_short": "Zener Diode BZT52C8V2 WD 8.2V (SOD-123)",
        },
        {
            "diode_type": "zener",
            "package": "sod_123",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "bzt52c9v1",
            "name_short": "Zener Diode BZT52C9V1 9.1V (SOD-123)",
        },
        {
            "diode_type": "zener",
            "package": "sod_123",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "mmsz5235b",
            "name_short": "Zener Diode MMSZ5235B 6.8V (SOD-123)",
        },
        {
            "diode_type": "zener",
            "package": "sod_123",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "mmsz5238b",
            "name_short": "Zener Diode MMSZ5238B 8.7V (SOD-123)",
        },
        {
            "diode_type": "zener",
            "package": "sod_123",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "mmsz5245b",
            "name_short": "Zener Diode MMSZ5245B 15V (SOD-123)",
        },
        {
            "diode_type": "zener",
            "package": "sod_123",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "mmsz5248b",
            "name_short": "Zener Diode MMSZ5248B 18V (SOD-123)",
        },
        {
            "diode_type": "zener",
            "package": "sod_323",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "mmsz5248bs",
            "name_short": "Zener Diode MMSZ5248BS 18V (SOD-323)",
        },
        {
            "diode_type": "zener",
            "package": "sod_323",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "mmsz5250bs",
            "name_short": "Zener Diode MMSZ5250BS 20V (SOD-323)",
        },
        {
            "diode_type": "schottky_dual_common_cathode",
            "package": "sot_23",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "bat54c",
            "name_short": "Dual Schottky Diode BAT54C (SOT-23)",
        },
        # Power dual Schottky rectifiers in the TO-220 body: the first
        # through-hole diode rows with a power package, plus the first
        # schottky_dual_independent type (two separate legs, MBR20200CT).
        {
            "diode_type": "schottky_dual_common_cathode",
            "package": "to_220",
            "manufacturer": "onsemi",
            "part_number": "mbr1545ctg",
            "name_short": "Dual Schottky Diode MBR1545CTG (TO-220)",
        },
        {
            "diode_type": "schottky_dual_independent",
            "package": "to_220",
            "manufacturer": "onsemi",
            "part_number": "mbr20200ctg",
            "name_short": "Dual Schottky Diode MBR20200CTG (TO-220)",
        },
        # C7241: ST 2x10A 100V common-cathode power Schottky in TO-220AB.
        {
            "diode_type": "schottky_dual_common_cathode",
            "package": "to_220",
            "manufacturer": "stmicroelectronics",
            "part_number": "stps20s100ct",
            "name_short": "Dual Schottky Diode STPS20S100CT (TO-220)",
        },
        {
            "diode_type": "switching_dual_common_anode",
            "package": "sot_23",
            "manufacturer": "jiangsu_changjing_electronics_technology_co_ltd",
            "part_number": "baw56",
            "name_short": "Dual Switching Diode BAW56 (SOT-23)",
        },
    ]

    for diode in diodes:
        option = {}
        option["taxonomy_2"] = "diode"
        option["taxonomy_3"] = diode["diode_type"]
        option["taxonomy_4"] = diode["package"]
        option["taxonomy_14"] = diode.get("manufacturer", "")
        option["taxonomy_15"] = diode["part_number"]
        if "name_short" in diode:
            option["name_short"] = diode["name_short"]
        options.append(option)


if __name__ == "__main__":
    main()
