M48
; DRILL file KiCad 10.99.0-3758-g2f18d95be7 date 2026-09-25T20:55:14
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-25T20:55:14+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.99.0-3758-g2f18d95be7
; #@! TF.FileFunction,NonPlated,1,16,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X-2.2Y11.065
X2.2Y11.065
T2
X-5.715Y11.43
X5.715Y11.43
M30
