M48
; DRILL file KiCad 10.99.0-3671-gbe90a7e200 date 2026-09-09T23:26:02
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-09T23:26:02+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.99.0-3671-gbe90a7e200
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.800
%
G90
G05
T1
X3.5Y26.5
X3.5Y3.5
X61.5Y26.5
X61.5Y3.5
M30
