M48
; DRILL file KiCad 10.99.0-3758-g2f18d95be7 date 2026-09-25T21:30:12
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-25T21:30:12+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.99.0-3758-g2f18d95be7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.000
%
G90
G05
T1
X6.247Y8.89
X9.247Y8.89
T2
X9.64Y26.5
X55.36Y26.5
T3
X3.5Y26.5
X3.5Y3.5
X61.5Y26.5
X61.5Y3.5
M30
