M48
; DRILL file KiCad 10.99.0-3758-g2f18d95be7 date 2026-09-13T17:12:10
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-13T17:12:10+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.99.0-3758-g2f18d95be7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.048
%
G90
G05
T1
X49.61Y4.734
X55.39Y4.734
T2
X9.642Y52.486
X55.362Y52.486
T3
X3.5Y52.5
X3.5Y3.5
X61.5Y52.5
X61.5Y3.5
M30
