M48
; DRILL file KiCad 10.99.0-3671-gbe90a7e200 date 2026-09-09T20:57:41
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-09T20:57:41+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.99.0-3671-gbe90a7e200
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X2.0Y18.5
X2.0Y2.0
X32.0Y18.5
X32.0Y2.0
M30
