M48
; DRILL file KiCad 10.99.0-3671-gbe90a7e200 date 2026-09-09T23:26:46
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-09T23:26:46+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.99.0-3671-gbe90a7e200
; #@! TF.FileFunction,NonPlated,1,16,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X-1.95Y20.828
X1.95Y20.828
T2
X-1.5Y-9.017
X1.5Y-9.017
M30
