M48
; DRILL file KiCad 10.99.0-3671-gbe90a7e200 date 2026-09-09T23:09:08
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-09T23:09:08+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.99.0-3671-gbe90a7e200
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.100
%
G90
G05
T1
X8.55Y35.184
T2
X4.0Y14.962
X4.0Y11.962
T3
X6.64Y2.518
X11.14Y2.518
M30
