M48
; DRILL file KiCad 10.99.0-3671-gbe90a7e200 date 2026-09-09T23:59:55
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-09T23:59:55+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.99.0-3671-gbe90a7e200
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.540
%
G90
G05
T1
X1.778Y12.93
X1.778Y9.93
T2
X2.54Y20.32
X2.54Y2.54
M30
