M48
; DRILL file KiCad 10.99.0-3758-g2f18d95be7 date 2026-09-21T17:09:32
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-21T17:09:32+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.99.0-3758-g2f18d95be7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X3.5Y44.5
X3.5Y3.5
X81.5Y44.5
X81.5Y3.5
M30
