M48
; DRILL file KiCad 10.0.6 date 2026-09-06T14:52:22
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-06T14:52:22+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X127.01Y-65.15
X132.79Y-65.15
T2
X103.9Y-64.1
X103.9Y-116.1
X155.9Y-64.1
X155.9Y-116.1
M30
