M48
; DRILL file KiCad 10.99.0-3671-gbe90a7e200 date 2026-09-10T01:28:13
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-10T01:28:13+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.99.0-3671-gbe90a7e200
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.540
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.400
%
G90
G05
T1
X4.025Y9.525
X15.025Y9.525
T2
X1.905Y1.27
X17.145Y17.78
T3
X4.525Y13.325
X9.525Y15.425
T4
X9.525Y9.525
M30
