M48
; DRILL file KiCad 10.99.0-3671-gbe90a7e200 date 2026-09-09T23:47:10
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-09T23:47:10+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.99.0-3671-gbe90a7e200
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X45.663Y14.32
X45.663Y8.54
T2
X14.118Y16.69
X14.118Y6.29
T3
X2.54Y20.955
X2.54Y1.841
M30
