M48
; DRILL file KiCad 10.99.0-3671-gbe90a7e200 date 2026-09-10T01:05:34
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-10T01:05:34+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.99.0-3671-gbe90a7e200
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C3.200
%
G90
G05
T1
X4.318Y40.05
X4.318Y36.15
T2
X4.191Y20.296
X4.191Y17.296
T3
X1.93Y7.772
T4
X6.43Y7.772
T5
X13.97Y2.54
X15.24Y50.8
X66.04Y35.56
X66.04Y7.62
M30
