M48
; DRILL file KiCad 10.99.0-3671-gbe90a7e200 date 2026-09-10T00:14:46
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-10T00:14:46+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.99.0-3671-gbe90a7e200
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X4.445Y13.38
X4.445Y9.48
T2
X48.26Y20.955
X48.26Y1.841
M30
