M48
; DRILL file KiCad 10.99.0-3758-g2f18d95be7 date 2026-09-21T19:24:39
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-21T19:24:39+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.99.0-3758-g2f18d95be7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X66.558Y35.514
T2
X15.758Y50.754
M30
