M48
; DRILL file KiCad 10.99.0-3758-g2f18d95be7 date 2026-09-21T21:41:28
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-21T21:41:28+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.99.0-3758-g2f18d95be7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.400
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C1.800
%
G90
G05
T1
X5.934Y65.142
X5.934Y62.142
T2
X42.0Y17.0
T3
X43.0Y59.5
T4
X38.5Y59.5
M30
