M48
; DRILL file KiCad 10.99.0-3671-gbe90a7e200 date 2026-09-10T00:07:23
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-10T00:07:23+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.99.0-3671-gbe90a7e200
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X5.645Y14.32
X5.645Y8.54
T2
X28.194Y12.93
X28.194Y9.93
M30
