M48
; DRILL file KiCad 10.99.0-3671-gbe90a7e200 date 2026-09-10T01:28:20
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-10T01:28:20+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.99.0-3671-gbe90a7e200
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.540
%
G90
G05
T1
X-4.826Y-5.162
X-4.826Y-9.062
T2
X17.145Y-5.461
X17.145Y-9.271
T3
X38.989Y1.778
X38.989Y-16.002
M30
