M48
; DRILL file KiCad 10.0.6 date 2026-09-06T19:16:31
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-06T19:16:31+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X112.38Y-77.86
X112.38Y-83.64
T2
X120.18Y-111.24
X121.45Y-62.98
X172.25Y-78.22
X172.25Y-106.16
M30
