M48
; DRILL file KiCad 10.99.0-3758-g2f18d95be7 date 2026-09-13T05:53:12
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-13T05:53:12+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.99.0-3758-g2f18d95be7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X23.427Y41.699
T2
X23.427Y20.599
T3
X15.24Y50.8
X66.04Y35.56
X66.04Y7.62
M30
